services:
    sio_test:
        user: app
        build:
            context: .
            args:
                USER_ID: ${USER_ID:-1000}
        depends_on:
            - postgres
        links:
            - postgres
        ports:
            - "8337:8337"
        volumes:
            - .:/app:rw
        environment:
            - APP_ENV=dev
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
volumes:
    db_data:
        driver: local